version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nodejs
      MYSQL_USER: nodejs
      MYSQL_PASSWORD: nodejs
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodejs
      MONGO_INITDB_ROOT_PASSWORD: nodejs
      MONGO_INITDB_DATABASE: nodejs